kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    cb.service: gocdb-database-pvc
  name: gocdb-database-pvc
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
