{{- if .Values.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ include "gocdb.fullname" . }}-ingress
  {{- if .Values.ingress.annotations }}
  annotations:
     {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
  - {{- if .Values.ingress.hostname }}
    host: {{ .Values.ingress.hostname }}
    {{- end }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ include "gocdb.fullname" . }}
          servicePort: 8080
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end -}}
