kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "gocdb.fullname" . }}-webserver
  labels:
    {{- include "gocdb.webserverLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gocdb.webserverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gocdb.webserverSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "gocdb.fullname" . }}-webserver
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}"
          imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: GOCDB_DATABASE_SERVER
              value: {{ include "gocdb.fullname" . }}-database
            {{- range $name, $value := .Values.webserver.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - mountPath: /var/www/html/gocdb/config/local_info.xml
              subPath: local_info.xml
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "gocdb.fullname" . }}-webserver-config
