url: "https://sciencemesh-test.uni-muenster.de/testdb"
defaultScope: "SM"

# Configure the service of the webserver
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  path: /testdb
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /

database:
  global:
    storageClass: cephfs
